### ISSUE TITLE
[Login] User can be logined after registration with not confirmed e-mail

### ISSUE THREAD

**Issue by UstymYarema** [ita-social-projects/horondi_client_fe#1070]
**Environment:** Windows 10, Google Chrome v.94.0.4606.81 (64)
**Reproducible:** always

**Preconditions**
http://horondi-front-staging.azurewebsites.net/login

**Steps to reproduce**

1. Go to http://horondi-front-staging.azurewebsites.net/register
2. Fill all mandatory fields with valid data
3. Click on 'Register' button
4. Click on 'Log in' in dropdown list
5. Enter all mandatory fields from 'Step 2'
6. Click on 'Log in' button

**Actual result**
New page is open. User can be logined after registration with not confirmed e-mail.

**Expected result**
User can't be logined after registration with not confirmed e-mail.

**User story and test case links**
E.g.: "User story #193
[Test case](https://jira.softserve.academy/browse/LVHRB-310)"

https://user-images.githubusercontent.com/92396050/137536307-2b83197c-fe23-4f98-b3da-72313a401f84.mp4

**Comment by MariiaDakh** [comment]
User is still able to log in without confirmed email
