### ISSUE TITLE
[Registration] Verify confirmation message in e-mail for correctness

### ISSUE THREAD

**Issue by UstymYarema** [ita-social-projects/horondi_client_fe#1191]
**Environment:** Windows 10, Google Chrome v.94.0.4606.81 (64)
**Reproducible:** always

**Preconditions**
http://horondi-front-staging.azurewebsites.net/cart

**Steps to reproduce**

1. Go to http://horondi-front-staging.azurewebsites.net/register
2. Fill all mandatory fields with valid data
3. Click on 'Register' button
4. Check your e-mail apllication from 'Step 2'
5. Find and open message from Horondi with confirmation registration

**Actual result**
Empty one of main fields near:
'Вітаємо! 
Ви успішно зареєструвались в нашому магазині, залишилося тільки 
підтвердити вашу електронну адресу:'
Link is not visible, but the button for redirection is working.

**Expected result**
In confirmation message all mandatory fields is fill correctly.

**User story and test case links**
E.g.: 
[Test case](https://jira.softserve.academy/projects/LVHRB?selectedItem=com.thed.zephyr.je:zephyr-tests-page#test-cycles-tab)"

![ApplicationFrameHost_WWbn7Gd1YI](https://user-images.githubusercontent.com/92396050/140332700-e7d86496-f940-4e48-9232-e3951bf7f683.png)

**Comment by mariia-matiiv** [comment]
There was no e-mail received after the registration.

**Comment by SirAndrii** [comment]
![image](https://user-images.githubusercontent.com/24919819/152339878-20fbc3e7-f2dc-4448-a8b9-f5b4c7a849ab.png)

Bug with emails were solved
