### ISSUE TITLE
(SP:1) Resovle login page error

### ISSUE THREAD

**Issue by Filiczini** [ita-social-projects/horondi_client_fe#1507]
Resolve error/errors on login page / register page.
![image](https://user-images.githubusercontent.com/51033321/146190536-61b4b144-f730-4d0d-86aa-08e9db17b1fe.png)

**Comment by ostgit12** [comment]
вже змерджено в development PR#1635 Anastasiia Afanasieva ( мала якесь завдання на цій сторінці і поміняла це error={Boolean(touched.password && t(errors.password))} у двох TextField, бо мій варіант був error={!!(touched.password && t(errors.password))}.
