### ISSUE TITLE
Fix styles in Log in, Reset password, New password

### ISSUE THREAD

**Issue by anemyro** [ita-social-projects/horondi_client_fe#1540]
Fix styles according to the Figma (https://www.figma.com/file/31cjkbgpUtNpcOhKM3Cp9O/horondi?node-id=7303%3A1306):

Bugs describtion (https://docs.google.com/spreadsheets/d/12P5AgSMLZywGaZsVRWR87HAODDG04-F7YM35R2qGeh4/edit#gid=1661224271)

LOGIN 
1. "Поле має бути заповнене" накладається на чекбокс 
2. Дуже великий розмір окна "Нічого не знайдено"

PASSWORD RESET 
1. "Відновлення паролю" - товщина шрифту, "електрона пошта" без зірочки, текс під полем вводу пошти відірваний від поля, назва кнопки "НАДІСЛАТИ"  
2.Чорна рамка інпута, текс під інпутом відірваний від поля 
3. Колір кнопки "Відправити" 

 NEW PASSWORD 
1.Місце розташування окна
2.Поїхав текст на полях вводу

**Comment by SirAndrii** [comment]
- [ ] Login
- [ ] password reset
- [ ] new password
Can't figure out how to change a frame color to blue at password reset.

**Comment by SirAndrii** [comment]
Password Reset - Can't figure out how to change a frame color to blue at password reset.

Дуже великий розмір окна "Нічого не знайдено" - it refers to header. Will look it after complete separate pages.

**Comment by SirAndrii** [comment]
the NewPassword mockup has a default background. Need the approval to change it.

**Comment by SirAndrii** [comment]
Can't get to the change password page dut to an error with wishlist: Uncaught Invariant Violation: Cannot match fragment because __typename property is missing: {"message":"WISHLIST_NOT_FOUND","statusCode":404}
