### ISSUE TITLE
[Backpacks. Rolltop] Spelling mistake in 'Rolltop pink'

### ISSUE THREAD

**Issue by mariia-matiiv** [ita-social-projects/horondi_client_fe#1571]
**Precondition**
Go to  https://horondi-front-staging.azurewebsites.net/
Switch to English language

**Steps to Reproduce**
1. Click on burger menu on the main page
2. In category 'BACKPACKS' select 'Rolltop'
3. Pay attention to 'Rolltop pink'

**Actual Result**
The item name is spelled 'Roltop pink'
![image](https://user-images.githubusercontent.com/96194957/147700740-653efc65-d562-466a-901e-0ba8533c0784.png)

**Expected Result**
The item name should be spelled 'Rolltop pink'.

**Comment by Skydry333** [comment]
this bug has already been fixed and is no longer reproducible
