### ISSUE TITLE
(SP:3)Create page “My Certificates”

### ISSUE THREAD

**Issue by byavdoshniak** [ita-social-projects/horondi_client_fe#1578]
Create page “My Certificates” according to FIGMA design. Button “Buy new Certificate”  should lead us to “Buy Gift certificate page”. Button “Add certificate” will open a modal window with input for certificate number and buttons “add” and “cancel”. Certificates in the table are sorted by date from newest to oldest.
Figma link: https://www.figma.com/file/31cjkbgpUtNpcOhKM3Cp9O/horondi?node-id=7303%3A1306

**Comment by anemyro** [comment]
Have been merged after request changes
