### ISSUE TITLE
[Cart icon] After removing all items from cart quantity of items still displayed on cart image on header 

### ISSUE THREAD

**Issue by MariiaDakh** [ita-social-projects/horondi_client_fe#1581]
**Preconditions**

1. Go to https://horondi-front-staging.azurewebsites.net/
2. Log in as a user

**Reprodusible:** Sometimes

**Steps to Reproduce:**
1. Add any item to the cart
2. Go to the cart and remove this item
3. Go to the main page
4. Pay attention to the cart image on the header

**Actual Result**: On the cart image displayed incorrect quantitiy of items when cart is empty
![image](https://user-images.githubusercontent.com/72098467/147744770-6ea7173d-5a43-4c3b-b644-b6109e02c118.png)
**Expected Result**: After removing all items from the cart number of items aren't displayed on icon

**Comment by byavdoshniak** [comment]
After we will merge pull request #1629 this bug will dissapear. A will notify you when we merge abovementioned
