### ISSUE TITLE
[Mobile version] The icon 'Account settings' is absent on the header

### ISSUE THREAD

**Issue by VeronikaChorna** [ita-social-projects/horondi_client_fe#1710]
Environment Windows 10, Chrome Version 96.0.4664.110
Reproducible: Always

**Preconditions:**

1. Go to https://horondi-front-staging.azurewebsites.net/
2. Log in as a user

**Steps to reproduce:**

1.  Open Chrome DevTools
2. Click Toggle Device Toolbar
3. Select any mobile device (Samsung Galaxy S8+)
4. Verify that icon 'Account settings' is present

**Actual result:** 'Account settings' is absent
![tert](https://user-images.githubusercontent.com/96176970/152188636-538d8fc6-42c4-4367-b7b6-d8c28e04da50.png)

**Expected result:** 'Account settings' is present in the mobile version

**Comment by OksanaTochyniuk** [comment]
Retesting was executed. Bug was fixed (09/04/2022).
