### ISSUE TITLE
[Account settings] No validation in the fields District and Apartment number

### ISSUE THREAD

**Issue by MariiaDakh** [ita-social-projects/horondi_client_fe#1809]
**Environment:** Google Chrome v.96.0.4664.110; OS Windows 10
**Reproducible:** always

**Preconditions**

1. Go to https://horondi-front-staging.azurewebsites.net/
2. Log in as a user

**Steps to reproduce:**
1. Click on profile icon on the header
2. Click on Account settings link
3. Enter invalid value in the District field (e.g. 211?//878322@454)
4. Enter invalid value in the Apartment number field (e.g aa2//@)
5. Click on the Save changes button
6. Pay attention to these fields

Actual result: Changes are saved, no error messages appear
![image](https://user-images.githubusercontent.com/72098467/153294687-64a5ae04-b653-4df6-b692-b8882688f459.png)

Expected result: After clicking on the button the fields highlighted in red, appear error messages: 'Field should contain letters, apostrophes, hyphens and spaces' near District field;  'This field should contain numbers' near Apartment number field

**Comment by OksanaTochyniuk** [comment]
Retesting was executed (10.04.2022). Bug was fixed.
