### ISSUE TITLE
[Customer Support Chat] The message is sent with an invalid email

### ISSUE THREAD

**Issue by MelnykQC668** [ita-social-projects/horondi_client_fe#1904]
Steps to reproduce:
1. Go to Horondi Home Page https://horondi-front-staging.azurewebsites.net/
2. Click on 'Customer Support Chat' icon
3. Click on 'E-mail' icon
4. Type data in 'Name' field (e.g. 'Roman')
5. Type email adrress like '1@r.net'
6. Type data into 'Text' field (e.g. 'Hello')
7. Clock on 'Send' button

Expected result:  Message is not sended, 
'Wrong email address, example@mail.com' error message should appears.
Actual result: Message is sended.

Environment: Windows 10, 21H2; Google Chrome 100.0.4896.127 (64-bit).

**Comment by Kharko7** [comment]
bug fixed in this issue #1932
