### ISSUE TITLE
[Catalog] The difference between price in catalog and price on product description page

### ISSUE THREAD

**Issue by MelnykQC668** [ita-social-projects/horondi_client_fe#1922]
1. Go to Horondi Home Page https://horondi-front-staging.azurewebsites.net/
2. Click on 'Backpacks' button in the 'Our Products' section.
3. Pay attention to the 'Roltop Red' price.
4. Click on the 'Roltop red' backpack.
5. Pay attention to the 'Roltop Red' price.

Actual result: The price is different than in the catalog.
Expected result: Price is the same.

Environment: Windows 10, 21H2 ; Google Chrome 100.0.4896.88 (64-bit).

**Comment by arm-and** [comment]
Fixed.Incorrect sizes and products have been removed from the database.
