### ISSUE TITLE
[Backpack new] Incorrect product description

### ISSUE THREAD

**Issue by MelnykQC668** [ita-social-projects/horondi_client_fe#1930]
Steps to reproduce:
1. Go to Horondi Home Page https://horondi-front-staging.azurewebsites.net/
2. Click on Backpacks link that located on 'Our Products' section
3. Click on 'Backpack new' model
4. Pay attention to the description of the color and pattern

Expected result: The color and pattern match the image of the backpack.
Actual result: The color and pattern don't match the image of the backpack (screenshot added).

Environment: Windows 10, 21H2 ; Google Chrome 100.0.4896.88 (64-bit).

**Comment by MelnykQC668** [comment]
![Screenshot_156](https://user-images.githubusercontent.com/101631366/167800976-88f91f9b-9b12-4f00-a5bb-54f1533656a0.png)

**Comment by Kharko7** [comment]
Fixed
