### ISSUE TITLE
[Account Menu] Second click on the User icon doesn't close menu

### ISSUE THREAD

**Issue by SazonenkoVictoriia** [ita-social-projects/horondi_client_fe#2082]
**Environment** Windows 10, Chrome Version 103.0.5060.134
**Reproducible:** Always

**Preconditions:**
Go to https://horondi-front-staging.azurewebsites.net/
Log in as User

**Steps to reproduce:**
Click on User icon to open Account Menu
Click on User icon second time to close Account Menu
Pay attention to the Menu

**Actual result:** When User clicks on User icon second time Account Menu doesn't close
https://user-images.githubusercontent.com/33963679/180157487-83450e41-8629-446c-96d9-88a38d9cc879.mp4

**Expected result:** When User clicks on User icon second time Account Menu should close

**Comment by vaishalparikh** [comment]
@SazonenkoVictoriia  I would like to take this issue and try fixing it.
