### ISSUE TITLE
(SP: 2) Create pop up after clicking on 'Gift certificate' icon

### ISSUE THREAD

**Issue by Tolik170** [ita-social-projects/horondi_client_fe#2122]
1) After clicking on 'Gift certificate' icon pop up window with the mandatory field for recipients email should appear and two buttons ‘Confirm’ and ‘Cancel’. Pop up window should contain 'X' button in right top corner in order to close the window.
2) Validation for email field should work according to the principles of registration on the website.
3)  Certificate should be attached to entered email, if certificate is allready attached to another email, you should unlink it and attached to entered email.
https://www.figma.com/file/r1buAi0edVZ9SyV9Y6Erax/Horondi_2022?node-id=15135%3A54698

**Comment by MickhaelSh** [comment]
Done
