### ISSUE TITLE
[SP: 0.5] [Cart] Fix styles in Cart page

### ISSUE THREAD

**Issue by Tolik170** [ita-social-projects/horondi_client_fe#2146]
1) Fix styles in Cart page.
2) Input field with total price and button should be located in center.

![image](https://user-images.githubusercontent.com/63456632/193242428-332ede3e-fd2e-411f-a567-71eb185e768f.png)
![image](https://user-images.githubusercontent.com/63456632/193242673-17a49974-3c3f-4306-971b-5aff2539f1f3.png)

**Comment by Gluharski** [comment]
Hey, I would like to contribute. Please, assign this issue to me.

**Comment by MarianCekan** [comment]
!assign
