### ISSUE TITLE
[Horondi Admin Portal] Sign out window has 'Видалити' label and 'Видалити' button instead of "Вихід"

### ISSUE THREAD

**Issue by kirkchernyshkov** [ita-social-projects/horondi_client_fe#391]
**Environment:** Windows 10 Home, Google Chrome Version 87.0.4280.88;
**Reproducible:** always;
**Build found:** last commit from https://github.com/ita-social-projects/horondi_client_fe
"Commit 52eb6ed0e34182e1501c973878c57d850a4ea8fa"

**Preconditions**

Go to https://horondi-admin-staging.azurewebsites.net
Log into Administrator page as Administrator

**Steps to reproduce**
1. Click on the 'Sign out' button
2. Pay attention to the 'Sign out' window

**Actual result**
Sign out window has 'Видалити' label and 'Видалити' button
![image](https://user-images.githubusercontent.com/75264827/102130201-3a88fe00-3e59-11eb-8948-fccf22a7808e.png)

**Expected result**
Sign out window has only one 'Вихід' label and "Вийти' button

**Comment by SerhiiDatsiuk** [comment]
![Change request1](https://user-images.githubusercontent.com/75260166/103156775-098fbe00-47b5-11eb-8f46-a1ad11f0bb3d.png)
