### ISSUE TITLE
[Категорії] Admin is not able to close 'Видалити категорію' pop-up window

### ISSUE THREAD

**Issue by kirkchernyshkov** [ita-social-projects/horondi_client_fe#400]
**Environment:** Windows 10 Home, Google Chrome Version 87.0.4280.88
**Reproducible:** always
**Build found:** "commit 65623ed"

**Preconditions**

Go to https://horondi-admin-staging.azurewebsites.net
Log into Administrator page as Administrator

**Steps to reproduce**

1.Click on 'Категорії' menu item
2. Click on the 'Delete' icon near any item

**Actual result**
"Видалити кaтегорію' pop-up window is opened and the admin can not cancel his action
![image](https://user-images.githubusercontent.com/75264827/102411328-6ee7f000-3ffa-11eb-8922-c2a2600ac71c.png)

**Expected result**
'Видалити категорію' pop-up window is opened and the admin can cancel his action

![image](https://user-images.githubusercontent.com/75264827/102724192-8da9f780-4316-11eb-86ac-d2b32a72488f.png)

**User story and test case links**
E.g.: "User story [LVHRB-15](https://jira.softserve.academy/browse/LVHRB-15)
[Test case](https://jira.softserve.academy/browse/LVHRB-27)"

**Comment by vic0803** [comment]
add new functionality with delete category:
ac1: button - icon with delete 
ac2: after delete category move to pending status for 90 days
ac3: possible to restore category
ac4: create additional category with move possibility 
ac5: possibly to move back - action after ac4 perform

**Comment by vic0803** [comment]
add new functionality with delete category:
ac1: button - icon with delete 
ac2: after delete category move to pending status for 90 days
ac3: possible to restore category
ac4: create additional category with move possibility 
ac5: possibly to move back - action after ac4 perform
