### ISSUE TITLE
['Cтворити гобелен'] Error occurs when creating a new gobelin with valid data

### ISSUE THREAD

**Issue by runner-on-waves** [ita-social-projects/horondi_client_fe#436]
**Environment:** Windows 10 Pro, Google Chrome Version 87.0.4280.88
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/horondi_client_fe/commit/79f564512280c35f406ccc4d53afe7d694394dd7

**Preconditions:**

Go to https://horondi-admin-staging.azurewebsites.net
Log into Administrator page as Administrator

**Steps to reproduce:**

1.Click on 'Гобелени' menu item
2. Click on 'Додати' button.
3. Add a photo (size no more than 15MB)
4. Enter valid data in all mandatory fields: 
   - from 2-30 characters into the field 'Код матеріалу' (Latin letters and numbers, e.g. test123).
   - from 3-50 characters into the field 'Назва'(Ukrainian letters, numbers, special symbols , e.g. 'Зорі#1').
   - from 3 to 1000 characters into the field  'Опис' (Ukrainian letters, numbers, special symbols , e.g. 'Зорі#1 - це ..').
   - from 3-50 characters into the field 'Name'(Latin letters, numbers, special symbols , e.g. 'Stars#1').
   - from 3 to 1000 characters into the field  'Description' (Latin letters, numbers, special symbols , e.g. 'Stars#1').
5. Press 'Зберегти' button.

**Actual result**
1. Button 'Зберегти' can be multiclicked(about 20 times) before it returns to 'Гобелени'.
2. An error message occurs 400 'Такий гобелен вже існує'. 
<img width="957" alt="Error when creating a gobelin" src="https://user-images.githubusercontent.com/75261055/103023983-a6552000-4557-11eb-8eb9-a26edfd61654.png">

**Expected result**
1. New gobelin is created and stored to the database.
2. It returns admin to the main page ‘Гобелени’.
3. Newly created gobelin is displayed in the catalogue of all gobelins.

[Test case](https://jira.softserve.academy/browse/GO-40)
[User Story](https://jira.softserve.academy/browse/LVHRB-7)

**Comment by ivan-bonk** [comment]
Disable 'save' button while saving data
Add loader bar
