### ISSUE TITLE
['Гобелени'] Editing functionality doesn't work, changes are not saved 

### ISSUE THREAD

**Issue by runner-on-waves** [ita-social-projects/horondi_client_fe#442]
**Environment:** Windows 10 Pro, Google Chrome Version 87.0.4280.88
**Reproducible:** always
**Build found:** https://github.com/ita-social-projects/horondi_client_fe/commit/79f564512280c35f406ccc4d53afe7d694394dd7

**Preconditions:**

Go to https://horondi-admin-staging.azurewebsites.net
Log into Administrator page as Administrator.
Click on 'Гобелени' menu item.

**Steps to reproduce:**

1. Choose any test gobelin from the catalogue and click on 'Edit' button.
2. Add a photo (size no more than 15MB)
3. Change data in mandatory fields: 

   - from 2-30 characters into the field 'Код матеріалу' (Latin letters and numbers, e.g. test123).
   - from 3-50 characters into the field 'Назва'(Ukrainian letters, numbers, special symbols , e.g. 'Зорі#1').
   - from 3 to 1000 characters into the field  'Опис' (Ukrainian letters, numbers, special symbols , e.g. 'Зорі#1 - це ..').
   - from 3-50 characters into the field 'Name'(Latin letters, numbers, special symbols , e.g. 'Stars#1').
   - from 3 to 1000 characters into the field  'Description' (Latin letters, numbers, special symbols , e.g. 'Stars#1').
5. Press 'Зберегти' button.

**Actual result**
1. Warning message in window 'Редагування' with the text 'Ви впевнені, що хочете зберегти зміни?' doesn't appear.
2. Button 'Зберегти' doesn't save changes and retuns value to initial state.
3. An admin is not returned to the 'Гобелени' page.

https://user-images.githubusercontent.com/75261055/103135850-1680b480-46c4-11eb-8d16-5ee46d47bbaf.mp4

**Expected result**
1. Warning message in window 'Редагування' with the text 'Ви впевнені, що хочете зберегти зміни?' should be displayed.
2. A gobelin is successfully edited and stored to the database.
3. It returns admin to the main page ‘Гобелени’.
<img width="161" alt="Warning message Editing correct" src="https://user-images.githubusercontent.com/75261055/103135837-f94be600-46c3-11eb-9ffc-3ad46ad10440.png">

[Test case](https://jira.softserve.academy/browse/LVHRB-62)
[User Story](https://jira.softserve.academy/browse/LVHRB-7)

**Comment by ivan-bonk** [comment]
Cannot reproduce
