### ISSUE TITLE
[Admin Login Page] The error message is not displayed in the 'Email' field when the User fill in special characters 

### ISSUE THREAD

**Issue by SerhiiDatsiuk** [ita-social-projects/horondi_client_fe#450]
**Environment:** Microsoft Windows 10,Chrome 87.0.4280.88
**Reproducible:** always
**Build found:** 79f5645

**Preconditions**
Clear cache and cookies

**Steps to reproduce**
1. Go to 'https://horondi-admin-staging.azurewebsites.net/login'
2. Navigate to the 'Email' and 'Password' fields
3. Fill in the 'Email' field with special characters E.g. '+++....!!!!!.......!!!!!.......!!!!!'
4. Leave the 'Password' field empty
5. Click the 'Увійти button

**Actual result**

**Expected result**

**User story and test case links**
"User story https://jira.softserve.academy/browse/LVHRB-10
[Test case]

**Comment by vic0803** [comment]
need remove double check  and double notification  of empty email field
