### ISSUE TITLE
Fix user registration

### ISSUE THREAD

**Issue by Kiyooooko** [ita-social-projects/horondi_client_fe#540]

**Comment by vic0803** [comment]
AC1 - fix spinner position to center 
AC2 - fix information window about successful registration ( change to popup information ) 
AC3 - delete success new page 
<img width="720" alt="Screenshot 2021-02-16 at 01 50 33" src="https://user-images.githubusercontent.com/23040566/108002805-67909300-6ff9-11eb-952d-c4afcdfccf5b.png">

**Comment by vic0803** [comment]
Need to define functionality for system and user flow
