### ISSUE TITLE
Fix adding to wishlist

### ISSUE THREAD

**Issue by yuliiakucher** [ita-social-projects/horondi_client_fe#666]
For a logged user, when we want to add an item to wishlist,

![image](https://user-images.githubusercontent.com/61886864/119037192-53727e00-b9ba-11eb-968e-dbafc0bc6543.png)

we get an error

![image](https://user-images.githubusercontent.com/61886864/119037053-2b831a80-b9ba-11eb-989e-bf6b79c47e84.png)

**Comment by grebiniuk** [comment]
Fixed in https://github.com/ita-social-projects/horondi_client_fe/pull/655
