### ISSUE TITLE
[Products Page. Sort by] Inconsistent items are displayed when sorting items by 'popularity'

### ISSUE THREAD

**Issue by olesmack** [ita-social-projects/horondi_client_fe#704]
**Environment:** Windows 10 Pro 64bit, Firefox 89.0 64bit
**Reproducible:** Always

**Pre-conditions:**
1. Go to https://horondi-front-staging.azurewebsites.net/
2. Open the 'Sort by' drop-down list

**Description:**
**Steps to reproduce:**

1. Choose 'popularity' from drop-down list

**Actual result:**
Inconsistent items are showed

**Expected result:**
The items are sorted by 'popularity'

[TC_STEP#1](https://jira.softserve.academy/browse/LVHRB-212)

**Comment by YaroslavBorzenkov** [comment]
The items are not sorted by 'popularity' on the second page.
![Screenshot_29](https://user-images.githubusercontent.com/86916836/147504870-4fb2a264-6e7b-485f-9cf6-40fc928e0a56.jpg)

**Comment by tarasSanotskyi** [comment]
Items are sorted by popularity, stars don`t mean popularity, it is a rating
