### ISSUE TITLE
[Product Detail Pages] 3 Pages are presented without 2 product recomendation for User

### ISSUE THREAD

**Issue by rrarock** [ita-social-projects/horondi_client_fe#720]
*Steps are relevant for 3 PDP on Product Catalog:

- "Ролтоп червоний"
- "Ролтоп чорний"
- "Сірий гаманець"

**Steps to reproduce** 

1. Go to: https://horondi-front-staging.azurewebsites.net/ 
2. Click to the menu on the left corner on the top of the pages 
3. Choose any point on "Рюкзаки" tab
4. Open "Сірий гаманець" product detail page
5. Scroll down page 
6. Pay attention, that page present just 1 of 3 recommendation for User before "Feedback" fields (Screen 1) as it realized on finished pages (Screen 2)

Screen 1
![Screen 1 PDP with 1 recommendations of 3](https://user-images.githubusercontent.com/84689435/121269195-12d69800-c8c8-11eb-83e2-cba16421d335.png)

Screen 2
![Screen 2 PDP with recommendation (2)](https://user-images.githubusercontent.com/84689435/121269200-1538f200-c8c8-11eb-846c-0bd7821b5f39.png)

**Actual result:**

Page "Сірий гаманець" present 1 recommendation of the product (called "Similar Items") with photo

**Expected result:**

All Product Detail Page shows to Users 3 recommendation of the product (called "Similar Items") with photo

**Comment by VeronikaChorna** [comment]
Pages are presented with only one product in the field "It fits well with" when you select"Red Rolltop", "Black Rolltop"
![tempsnip](https://user-images.githubusercontent.com/96176970/147507533-2dd88288-360a-4792-91a9-5296b0f15a5d.png)

**Comment by tarasSanotskyi** [comment]
the similar products are working as follows: 
it filter similar product according to pattern, color and main material
amount of similar products items can be less than 3
