### ISSUE TITLE
[Product Deatail Page - EN] Inccorect error message appears when user send Feedback with empty fields

### ISSUE THREAD

**Issue by rrarock** [ita-social-projects/horondi_client_fe#729]
**Steps to reproduce:**

1. Go to: https://horondi-front-staging.azurewebsites.net/ 
2. Click to the menu on the left corner on the top of the pages 
3. Choose any point on "Рюкзаки" tab
4. Open "Роллтоп синій" product detail page
5. Switch page to the English version by button on right corner on top of the page
6. Scroll page down 
7. Leave all Feedback fields empty
8. Click to the button "Leave Feedback"
9. Pay attention to the error message on Feedback fields

**Actual result:**

Error message appears under each Feedback fields, and it is related just for their fields (Screenshot 1)

**Expected result:**

An error message  :  "All fields must be filled" (Mockup 2) is displayed above the button  "Leave feedback"

Mockup 2
![Mockup_2_Error message](https://user-images.githubusercontent.com/84689435/121517676-53353380-c9f8-11eb-90ea-04e639a9171d.png)

Screenshot 1 
![Screenshot 1 Inccorect error message ](https://user-images.githubusercontent.com/84689435/121517731-60522280-c9f8-11eb-86f3-03c21d8aeb1b.png)

*Steps are relevant for all PDP on Product Catalog:

- "Ролтоп синій"
- "Ролтоп жовтий"
- "Ролтоп червоний"
- "Ролтоп чорний"
- "Червона бананка"
- "Сірий гаманець"
- "Сумка шопер"
- "Рюкзак новий"

**Comment by VeronikaChorna** [comment]
No longer valid. The design was changed.
