### ISSUE TITLE
[Cart] Inconsistent order quantity can be set

### ISSUE THREAD

**Issue by olesmack** [ita-social-projects/horondi_client_fe#748]
Environment: Windows 10 Pro 64bit, Firefox 89.0 64bit
Reproducible: always

Pre-conditions:
1. Go to https://horondi-front-staging.azurewebsites.net/
2. Go to Menu->Backpack->Rolltops
3. Choose Rolltop blue
4. Click 'Buy now' button

Description:
Steps to reproduce:

1. Choose any delivery type (e. g. Ukr Post)
2. Navigate to the 'Quantity' textbox and input inconsistent value (e. g. 10 000 000 000)

Actual result:
The order quantity of 10 000 000 000 is set

Expected result:
The maximum order quantity is 1000

https://github.com/ita-social-projects/horondi_client_fe/issues/148

![Untitled](https://user-images.githubusercontent.com/84582793/122616352-e4f50e80-d092-11eb-8c28-0cd649387e53.png)

**Comment by Skrekliam** [comment]
Max result now is 1000
