### ISSUE TITLE
[Order. Delivery Address] Error message is not displayed when typing inconsistent values

### ISSUE THREAD

**Issue by olesmack** [ita-social-projects/horondi_client_fe#751]
Environment: Windows 10 Pro 64bit, Firefox 89.0 64bit
Reproducible: always

Pre-conditions:

1. Go to https://horondi-front-staging.azurewebsites.net/
2. Go to Menu->Backpack->Rolltops
3. Choose Rolltop blue
4. Click 'Buy now' button

Description:
Steps to reproduce:

1. Choose delivery type with a courier (e. g. Ukr Post courier)
2. Click on 'Go to checkout'
3. Fill out the 'City' text box with inconsistent values (@#$580)
4. Fill out the 'Steet' text box with inconsistent values (@#$580)
5. Fill out the 'Building' text box with inconsistent values (@#$qwerty)
6. Fill out the 'Apartment' text box with inconsistent values (@#$qwerty)

Actual result:
1. The 'City', 'Steet', text boxes are filled out with inconsistent values @#$580
2. The 'Building', 'Apartment' text boxes are filled out with inconsistent values @#$qwerty

Expected result:
1. The error messages 'Field should contain only letters' for the 'City' and 'Steet' text boxes are displayed
2. The error message 'Field should contain only numbers' for the 'Building' and 'Apartment' text boxes are displayed

https://github.com/ita-social-projects/horondi_client_fe/issues/148

**Comment by MariiaDakh** [comment]
Error messages aren't displayed near fields after entering invalid values
