### ISSUE TITLE
[Checkout] Confirmation doesn't work when 'Apartment' text box is empty

### ISSUE THREAD

**Issue by olesmack** [ita-social-projects/horondi_client_fe#752]
Environment: Windows 10 Pro 64bit, Firefox 89.0 64bit
Reproducible: always

Pre-conditions:

1. Go to https://horondi-front-staging.azurewebsites.net/
2. Go to Menu->Backpack->Rolltops
3. Choose Rolltop blue
4. Click 'Buy now' button

Description:
Steps to reproduce:

1. Choose delivery type with a courier (e. g. Ukr Post courier)
2. Click on 'Go to checkout'
3. Fill out all the text boxes with valid data, except the 'Appartment'
4. Leave the 'Appartment' text box empty
5. Choose the 'Payment method' (e. g. Cash)
6. Click on 'Confirm order' button

Actual result:
The order is not created. The error page is opened

Expected result:
The order is created

https://github.com/ita-social-projects/horondi_client_fe/issues/148

![1](https://user-images.githubusercontent.com/84582793/123013974-ea719200-d3cd-11eb-90f8-503c5c56a81d.png)

![2](https://user-images.githubusercontent.com/84582793/123013976-eb0a2880-d3cd-11eb-87fd-0954b4489eca.png)

**Comment by MariiaDakh** [comment]
The page is still crash after clicking on "Confirm order" button
