### ISSUE TITLE
[Your Checkout Delivery page] delivery amount is not shown when user chose delivery by Nova poshta courier

### ISSUE THREAD

**Issue by NataliaAndriiets** [ita-social-projects/horondi_client_fe#765]
**Environment:** 
Windows 10 Home edition, 20H2 browser Google Chrome Version 91.0.4472.77 (Official Build) (64-bit).
 Reproducible: always.
 Build found: last commit 5e32bd7"
**Preconditions:**  
1.	Go to https://horondi-front-staging.azurewebsites.net/
2.	Register as user
3.	Choose a product from main menu catalog (e.g.- Bag shopper)
4.	Add the chosen product to the shopping cart
5.	Click the button “Buy now”

**Steps to reproduce:**
1.	Click on the cart label in the right top corner of the page 
2.	Choose delivery type Nova Poshta courier
3.	Click ‘Go to checkout’ button on the Your Cart-Checkout page
4.	Pay attention to the information about total price, delivery amount, total amount
**Actual result:**    
 
![image](https://user-images.githubusercontent.com/84592689/123948458-17174200-d9aa-11eb-8d27-23fda1da9858.png)

**Expected result:**   
1.	When the user had chosen Nova post courier delivery the user sees the delivery amount, the amount of goods, and the total amount.
2. 
User story and test case links E.g.: "User story #148
Labels to be added "Bug", Priority ("Medium"), Severity ("Major"), Type ("UI,).

**Comment by mariia-matiiv** [comment]
**Preconditions see above**
**Steps to Reproduce:**
1. Click "Buy Now"
2. Click "Go to Checkout"
3. Fill all mandatory fields with valid data
4. Select delivery method "Courier"
5. Idicate delivery address
6. Select payment method
7. Click "Confirm Order"

**Actual Result**
The delivery cost is not shown and the page crashes after clicking "Confirm Order" (please see the sceenshot attached).

![image](https://user-images.githubusercontent.com/96194957/147552749-4f1dcec0-a07d-4e9f-90f6-1a89a13cdca8.png)
