### ISSUE TITLE
[Registration page] The user is not registered when he confirms email by clicking the button in the Email confirmation letter

### ISSUE THREAD

**Issue by NataliaAndriiets** [ita-social-projects/horondi_client_fe#783]
**Environment:** 
Windows 10 Home edition, 20H2 browser Google Chrome Version 91.0.4472.77 (Official Build) (64-bit).
 **Reproducible:** on the second registration of the user which was registred before
 Build found: last commit 5e32bd7"
**Preconditions:**
1.	Go to https://horondi-front-staging.azurewebsites.net/register
2.	Set valid credentials to the 'Firstname' field (e.g. - 'Irynaa')
3.	Set valid credentials to the 'Lastname' field (e.g. - 'Gogott')
4.	Set valid credentials to the 'Password' field (e.g. - 'W123456')
5.	Fill in valid credentials to the 'Email' field 
6.	Click on the 'Register' button
7.	Confirm registration by clicking button “підтвердити E-mail” or link below “підтвердити E-mail” in the Confirmation letter
8.	  Check whether the user with credentials (firstname, lastname, e-mail) is cleaned from database in admin part 

**Steps to reproduce:**
1.	Go to https://horondi-front-staging.azurewebsites.net/register
2.	Set valid credentials to the 'Firstname' field (e.g. - 'Irynaa')
3.	Set valid credentials to the 'Lastname' field (e.g. - 'Gogott')
4.	Set valid credentials to the 'Password' field (e.g. - 'W123456')
5.	Fill in valid credentials to the 'Email' field (the same e-mail as in the preconditions)
6.	Click on the 'Register' button
7.	Confirm registration by clicking button “підтвердити E-mail” or link below “підтвердити E-mail” in the Confirmation letter

**Actual result:**
1. User is not found (see the attached screen) 
2. Response {"data":{"confirmUserEmail":{"message":"USER_NOT_FOUND","statusCode":404}}} is shown in ‘Network’ devtools
3.  New user is not registered in the database

**Expected result:**
1.	New user is registered
2.	New user is present in database of the adminpart.

User story and test case links E.g.: "User story #34, #35, #148
Labels to be added "Bug", Priority ("High'), Severity ("Major"), Type ("Functional').

**Comment by NataliaAndriiets** [comment]
![Снимок экрана (704)](https://user-images.githubusercontent.com/84592689/124605816-f9981b80-de74-11eb-81b7-4f94883cf017.png)

**Comment by OksanaTochyniuk** [comment]
**Update** of the defect #783 (18.04.2022)
_The user is not registered when he confirms email by clicking "CONFIRM E-MAIL" button or by clicking link in the confirmation letter_

**Environment:**
OS Windows 10 Pro (Version 10.0.19043), Google Chrome Version 98.0.4758.82 (64-bit)
**Reproducible**: always during the registration of user which was not registered before

**Preconditions:**
User was not registered before in the system.

**Steps to reproduce:**
1.	Go to “Registration” page https://horondi-front-staging.azurewebsites.net/register
2.	Enter valid data in the 'Firstname' field (e.g. ‘Oksana’)
3.	Enter valid data in the 'Lastname' field (e.g. 'Test')
4.	Fill in valid data in the 'Email' field
5.	Enter valid password in “Password” field- from 6 to 30 characters with one capital letter and one digit (e.g. ‘Qwerty123’)
6.	Enter the same password as in the step 5 of this defect in “Confirm the password field” (e.g. ‘Qwerty123’)
7.	Click on the 'Registration' button
8.	Open the mailbox which was indicated in the 'Email' field during the registration ( Step 4)
9.	Confirm registration by clicking button “CONFIRM E-MAIL” or link below  in the Confirmation letter. 

**Actual result:**
1.	Horondi website is open and dialog box with message “Oops! Something went wrong. Please, try again later” appears (pl. see the attached video).
2.	Email was not confirmed. New user is not registered in the system.

**Expected result:**
1.	Horondi website is open and dialog box with error message doesn’t appear.
2.	Email was confirmed. New user is registered in the system. 

The defect links to User story [#34](https://github.com/ita-social-projects/horondi_client_fe/issues/34)  (GitHub) / [LVHRB-191](https://jira.softserve.academy/browse/LVHRB-191) (Jira)






https://user-images.githubusercontent.com/101739835/163790933-d398579e-b245-45ff-9b3e-aefc08117932.mp4
