### ISSUE TITLE
[Product Detail Page]  The user can't  choose any product from product list.

### ISSUE THREAD

**Issue by AndriiVasylkiv** [ita-social-projects/horondi_client_fe#849]
**Environment:**  Windows 10 Chrome.
**Reproducible:**  always, 

**Pre-condition:**
log in with your current name and password.

**Steps to reproduce**

1. Go to https://horondi-front-staging.azurewebsites.net/login
2. login with your current name and password.
3. Click on 'Burger menu' on the top left
4. Choose 'Рюкзаки' ----> 'Ролтоп'
5. Click on any backpack.

**Actual result**
Error message 'Oops! Something went wrong. Please, try again later.'

**Expected result**
The chosen product is shown.

**User story and test case links**
 "User story #85 

https://user-images.githubusercontent.com/87528133/128330609-67be7bd4-4367-42b9-8c81-4c9aa4581d1e.mp4

**Comment by Volodymyr-Kozyra** [comment]
step 5 Click on any backpack. (e.g. Roltop Gray)

Actual result
Error message 'Oops! Something went wrong. Please, try again later.'

Expected result
The chosen product is shown.
