### ISSUE TITLE
[Slider] Web page is crashed when click on the 'See more' link

### ISSUE THREAD

**Issue by Volodymyr-Kozyra** [ita-social-projects/horondi_client_fe#953]
**Environment:** OS Microsoft Windows 10 LTSC, Chrome 94.0.4606.71 (64 bit)
**Reproducible:** always

**Preconditions**
Go to http://horondi-front-staging.azurewebsites.net/

**Steps to reproduce**

1. Click on 'Slider' tab in the menu
2. Click on third slide
3. Click on 'See more' link

**Actual result**
Error page with 'Oops!' are shown
Attached bug video recorded.

**Expected result**
Page with information are open

https://user-images.githubusercontent.com/91191125/135694272-730fba81-08c9-4cb6-ab8b-8f0b07fedd7d.mp4

**Comment by mariia-matiiv** [comment]
"Slider" has been updated and "See more" link is no longer present.
